name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"  

      # For deploying on GitHub Pages we need to use a path prefix
      # The pathprefix is the repo name (https://your-username.github.io/<PATH-PREFIX>/)
      # See: https://www.11ty.dev/docs/config#deploy-to-a-subdirectory-with-a-path-prefix
      # Thanks to https://stackoverflow.com/a/61560798/809939
      - name: Install and Build for Github Pages 🔧
        run: |
          echo ${GITHUB_REPOSITORY#*/}
          npm install
          npm run build -- --pathprefix '${GITHUB_REPOSITORY#*/}'

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: _site #the static site folder

      # If you need more privacy / no tracking,
      # sync your site to your own webspace
      # https://github.com/marketplace/actions/ftp-deploy

      # Build again if you need another path prefix (or just delete everything after --)
      # - name: Install and Build for FTP 🔧
      #   run: |
      #    npm install
      #    npm run build -- --pathprefix 'your-subdirectory/'

      #- name: 📂 Sync files
      #  uses: SamKirkland/FTP-Deploy-Action@4.1.0
      #  with:
      #    server: ftp.samkirkland.com
      #    username: myFtpUserName
      #    password: ${{ secrets.ftp_password }}